### ISSUE TITLE
Appropriate JaVers version for Spring Boot 2.7.8 and Java 17

### ISSUE THREAD

**Issue by azharakbar** [javers/javers#1404]
**Clear description of my expectations versus reality**
Hi,
We were using JaVers in our Spring boot application with the below versions
JaVers: 6.0.0
Spring Boot: 2.5.12
Java: 11

All were working perfectly fine

But now, we have done update to our Java and Spring boot versions as follows
Spring Boot: 2.7.8
Java: 17

With this configuration, we get the below error
```
Error creating bean with name 'JaversFromStarter' defined in class path resource [org/javers/spring/boot/sql/JaversSqlAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/google/gson/internal/LinkedHashTreeMap","logger":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext","thread":"main","level":"WARN","levelVal":30000}
{"timestamp":"2024-08-07T14:12:18.865Z","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","thread":"main","level":"INFO","levelVal":20000
```
To what version of JaVers should we update so that it will work with Java 17 and Spring Boot 2.7.8

**Comment by bartoszwalacik** [comment]
Hi, always to latest, see now https://javers.org/release-notes
